"""
Django settings for a_core project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _strip_wrapping_quotes(value: str) -> str:
    value = (value or "").strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"', "`"):
        return value[1:-1].strip()
    return value


def _load_env_file(file_path: Path) -> None:
    try:
        content = file_path.read_text(encoding="utf-8")
    except Exception:
        return

    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key:
            continue
        if key in os.environ:
            continue
        os.environ[key] = _strip_wrapping_quotes(value)


_env_file = os.getenv("DJANGO_ENV_FILE", "").strip()
_env_candidates: list[Path] = []
if _env_file:
    _env_candidates.append(Path(_env_file))
_env_candidates.extend(
    [
        BASE_DIR / "messenger.env",
        BASE_DIR / ".env",
        Path("/etc/messenger/messenger.env"),
        Path("/etc/pesk-messenger/pesk-messenger.env"),
    ]
)
for _p in _env_candidates:
    if _p.exists():
        _load_env_file(_p)
        break


def _env_bool(name: str, default: str = "0") -> bool:
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


def _env_csv(name: str) -> list[str]:
    raw = _strip_wrapping_quotes(os.getenv(name, ""))
    if not raw:
        return []
    return [_strip_wrapping_quotes(item) for item in raw.split(",") if item.strip()]


# Project title displayed in the header
PROJECT_TITLE = "Pesk Messenger"

_app_version_env = (_strip_wrapping_quotes(os.getenv("APP_VERSION", "dev")) or "").strip() or "dev"
if _app_version_env == "dev":
    try:
        _app_version_env = f"dev-{int((BASE_DIR / 'templates' / 'base.html').stat().st_mtime)}"
    except Exception:
        _app_version_env = "dev"
APP_VERSION = _app_version_env
APP_RESET_REQUIRED = _env_bool("APP_RESET_REQUIRED", "0")
APP_RESET_MESSAGE = (_strip_wrapping_quotes(os.getenv("APP_RESET_MESSAGE", "")) or "").strip()


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-rj#-z^kx3j+1ay397otg6j8m_8#v^$^$jys6&41vy^&6le)ezc",
).strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", "1")

OFFLINE_MODE = _env_bool("OFFLINE_MODE", "0")
IGNORE_NAVIGATOR_ONLINE = _env_bool("IGNORE_NAVIGATOR_ONLINE", "1" if DEBUG else "0")

ALLOWED_HOSTS = _env_csv("DJANGO_ALLOWED_HOSTS") or ['localhost', '127.0.0.1', '*']

CSRF_TRUSTED_ORIGINS = _env_csv("DJANGO_CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
    'django_htmx',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'a_rtchat',

    # My apps
    'a_home',
    'a_users',
    
    # Third party
    'django_browser_reload',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]
if DEBUG:
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware']


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'a_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'a_home.cprocs.project_title',
            ],
        },
    },
]

# WSGI_APPLICATION = 'a_core.wsgi.application'
ASGI_APPLICATION = 'a_core.asgi.application'


# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer"
#     },
# }

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv("REDIS_HOST", "localhost").strip() or "localhost", int(os.getenv("REDIS_PORT", "6379")))],
        },
    },
}



# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

_use_postgres = bool(
    os.getenv("POSTGRES_HOST")
    or os.getenv("POSTGRES_DB")
    or os.getenv("POSTGRES_USER")
    or os.getenv("POSTGRES_PASSWORD")
    or os.getenv("DATABASE_HOST")
    or os.getenv("DATABASE_NAME")
    or os.getenv("DATABASE_USER")
    or os.getenv("DATABASE_PASSWORD")
)

if _use_postgres:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": (os.getenv("DATABASE_NAME") or os.getenv("POSTGRES_DB") or "chat_db").strip(),
            "USER": (os.getenv("DATABASE_USER") or os.getenv("POSTGRES_USER") or "postgres").strip(),
            "PASSWORD": (os.getenv("DATABASE_PASSWORD") or os.getenv("POSTGRES_PASSWORD") or "").strip(),
            "HOST": (os.getenv("DATABASE_HOST") or os.getenv("POSTGRES_HOST") or "localhost").strip() or "localhost",
            "PORT": (os.getenv("DATABASE_PORT") or os.getenv("POSTGRES_PORT") or "5432").strip() or "5432",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.getenv("SQLITE_PATH", str(BASE_DIR / "db.sqlite3")),
        }
    }




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fa'

LANGUAGES = [
    ('fa', 'فارسی'),
]

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' 

WEBPUSH_VAPID_PUBLIC_KEY = os.getenv("WEBPUSH_VAPID_PUBLIC_KEY", "").strip()
WEBPUSH_VAPID_PRIVATE_KEY = os.getenv("WEBPUSH_VAPID_PRIVATE_KEY", "").strip()
WEBPUSH_VAPID_CLAIMS_SUB = os.getenv("WEBPUSH_VAPID_CLAIMS_SUB", "").strip()

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'


# --- allauth: offline / no-email-verification ---
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_CONFIRM_EMAIL_ON_GET = False  # احتیاطی
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/"  # اختیاری 

EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'

ACCOUNT_LOGIN_METHODS = {'username'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'password1*', 'password2*']
ACCOUNT_PHONE_VERIFICATION_ENABLED = False
ACCOUNT_FORMS = {
    "signup": "a_users.allauth_forms.PhoneSignupForm",
    "login": "a_users.allauth_forms.PhoneLoginForm",
}

CHAT_PUBLIC_CHAT_VISIBLE_TO_ALL = _env_bool("CHAT_PUBLIC_CHAT_VISIBLE_TO_ALL", "0")

try:
    from .local_settings import *  # noqa: F403
except Exception:
    pass

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", "1")
    SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", "1")
    CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", "1")
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "0"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "0")
    SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", "0")
