# Generated by Django 5.2.4 on 2026-02-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0008_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='group_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=160, null=True, unique=True),
        ),
    ]
