# Generated by Django 5.2.4 on 2026-02-06 17:17

import shortuuid
from django.db import migrations
from django.utils.text import slugify


def populate_group_slug(apps, schema_editor):
    ChatGroup = apps.get_model("a_rtchat", "ChatGroup")

    for group in ChatGroup.objects.all().iterator():
        if group.group_slug:
            continue

        if group.group_name in {"public_chat", "online-status"}:
            base = group.group_name
        elif group.groupchat_name:
            base = slugify(group.groupchat_name, allow_unicode=True)
        elif group.is_private:
            base = ""
            try:
                members = list(group.members.all())
            except Exception:
                members = []

            if len(members) == 2:
                usernames = sorted([m.username for m in members if getattr(m, "username", None)])
                if len(usernames) == 2:
                    base = slugify(f"dm-{'-'.join(usernames)}")
        else:
            base = ""

        base = (base or "").strip() or group.group_name
        base = base[:160]

        candidate = base
        while ChatGroup.objects.filter(group_slug=candidate).exclude(pk=group.pk).exists():
            suffix = shortuuid.uuid()[:8]
            cut = 160 - (len(suffix) + 1)
            candidate = f"{base[:cut]}-{suffix}"

        group.group_slug = candidate
        group.save(update_fields=["group_slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("a_rtchat", "0009_chatgroup_group_slug"),
    ]

    operations = [
        migrations.RunPython(populate_group_slug, migrations.RunPython.noop),
    ]

