# Generated by Django 5.2.4 on 2026-02-15 13:29

from django.conf import settings
from django.db import migrations, models


def _backfill_chatgroup_admins(apps, schema_editor):
    ChatGroup = apps.get_model("a_rtchat", "ChatGroup")
    for g in ChatGroup.objects.exclude(admin_id=None).only("id", "admin_id"):
        g.admins.add(g.admin_id)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0012_alter_chatstate_last_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_in_chat_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(_backfill_chatgroup_admins, _noop_reverse),
    ]
