# Generated by Django 5.2.4 on 2026-07-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0013_chatgroup_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_avatars/'),
        ),
    ]
