# Generated by Django 5.2.4 on 2026-07-16 17:34

import a_rtchat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0016_groupmessage_is_pinned_groupmessage_pinned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, storage=a_rtchat.models.KeepOriginalNameStorage(), upload_to=a_rtchat.models.chat_file_upload_to),
        ),
    ]
