# Generated by Django 5.2.4 on 2026-07-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0017_alter_groupmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='sticker',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
