# Generated by Django 5.2.4 on 2026-07-27 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0018_groupmessage_sticker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='pin_allowed_users',
            field=models.ManyToManyField(blank=True, related_name='pin_allowed_in_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='pin_policy',
            field=models.CharField(choices=[('admins', 'only admins'), ('all', 'all members'), ('selected', 'admins and selected members')], default='admins', max_length=16),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='pin_locked',
            field=models.BooleanField(default=False),
        ),
    ]
